- name: Vercel Preview Deployments
  # You may pin to the exact commit or the version.
  # uses: snaplet/vercel-action@5ac5d20a411195b1094d2490813999739f2af5ba
  uses: snaplet/vercel-action@v2.0.0
  with:
    # Await for the deployment to be ready and output the deployment URL
    await-for-deployment: # optional
    # Delete the preview related data on Vercel
    delete: # optional
    # Environment variables to create on Vercel, they are scoped to the "preview" environment and the current branch
    env: # optional
    # Command set for the Ignored Build Step in your project settings, the default script is canceling every preview deployments coming from the Vercel GitHub App.
    ignored-build-command: # optional, default is curl -sS "https://raw.githubusercontent.com/snaplet/vercel-action/v2/scripts/ignore-build.mjs" | node --input-type=module
